### PR TITLE
Indoor directions now display only on the floor associated with those directions

### LINKED ISSUE #200: Indoor directions display underneath indoor maps
Steps to reproduce:
- Click on the search button
- Enter "Consultation room" and click on the 1st result
- Click "use current location"
- Wait for directions activity to load
- Click and drag the screen a bit

Expected
- You can see indoor directions

Actual
- The polyline for indoor directions is hidden under the indoor maps

### PR DESCRIPTION
**Pull request by felixlapierre**
Fixes #200 

This will probably create some major merge conflicts in anything using PathPolyline or IndoorSegment

In summary, I added an event listener to ChangeFloor that notifies whenever the floor changes. I made DirectionsActivity listen to this event and save the current floor. When you add a PathPolyline to the map, it will display indoor directions for the current floor on top of the indoor maps, and other directions underneath the indoor maps. In addition, the path is re-drawn whenever the floor is changed.

This also required refactoring the Segment class to return a new data class, which i called Path, that holds the list of LatLng and also the floor of that Path. That is the change that will probably cause a lot of conflicts.

This feature could probably also use some refactoring.

### CODE REVIEW

File: app/src/main/java/com/example/campusguide/directions/indoor/IndoorPath.kt [hunk 1]
```diff
@@ -0,0 +1,10 @@
+package com.example.campusguide.directions.indoor
+
+import com.example.campusguide.directions.Path
+import com.google.android.gms.maps.model.LatLng
+
+class IndoorPath(points: MutableList<LatLng>, val floor: Int) : Path(points) {
+    override fun shouldDisplay(currentFloor: Int): Boolean {
+        return currentFloor == floor
+    }
+}
```
Comment (jun-loke) [inline app/src/main/java/com/example/campusguide/directions/indoor/IndoorPath.kt:10]: Do we need a whole class just for this? explain

File: app/src/main/java/com/example/campusguide/directions/indoor/Graph.kt [hunk 2]
```diff
@@ -13,13 +13,13 @@ class Graph constructor(building: Building) {
     init {
         // Add all rooms to the map
         building.rooms.forEach { room ->
-            val floor = room.code[0].toInt()
+            val floor = room.code.substring(0, 1).toInt()
```
Comment (jun-loke) [inline app/src/main/java/com/example/campusguide/directions/indoor/Graph.kt:16]: Can you explain what's happening here?

**Review by jun-loke — CHANGES_REQUESTED** [review]
The path nodes don't correspond to the images but this does fix the path display bug and floor specific path bug
Left comments. Will approve after explanation

File: app/src/main/java/com/example/campusguide/directions/indoor/IndoorPath.kt (hunk 1 above)
Comment (felixlapierre) [reply app/src/main/java/com/example/campusguide/directions/indoor/IndoorPath.kt:10]: The problem i wanted to solve: only indoor paths need to decide whether they should display based on what the floor number is.
Rather than use an IF statement or something to check if it's an indoor path I took advantage of polymorphism.
So we need a whole class to make the code extensible (if we need more kinds of paths and reasons to not display) and to split responsibilities (not put an if chain in one class)

File: app/src/main/java/com/example/campusguide/directions/indoor/Graph.kt (hunk 2 above)
Comment (felixlapierre) [reply app/src/main/java/com/example/campusguide/directions/indoor/Graph.kt:16]: This is to fix a bug that went unnoticed before because floor numbers weren't actually used
Red line = turns a character into an int, which gives you the char code instead of the number it represents. So "200.01" is considered to be on floor 50 since the char code for 2 is 50
Green line = turns the string into an int, which works properly. So "200.01" is considered to be on floor 2

File: app/src/main/res/layout/activity_directions.xml [hunk 3]
```diff
@@ -187,7 +223,12 @@
                     android:gravity="center_vertical"
                     android:paddingLeft="6dp"
                     android:text="Start"
+<<<<<<< HEAD
+                    android:textColor="@android:color/white" />
+
+=======
                     android:textColor="@android:color/white"/>
+>>>>>>> 3002ea1a88e585e2921ecd90acd907585ed1f1d8
```
Comment (jun-loke) [inline app/src/main/res/layout/activity_directions.xml]: This

File: app/src/main/res/layout/activity_directions.xml [hunk 4]
```diff
@@ -203,4 +244,5 @@
         </LinearLayout>
     </FrameLayout>
 
+    >>>>>>> 4406e743d679c32adb7e7460816b85022dd04698
```
Comment (jun-loke) [inline app/src/main/res/layout/activity_directions.xml]: ditto

**Review by jun-loke — CHANGES_REQUESTED** [review]

**Review by jun-loke — APPROVED** [review]
Good work!
